CREATE TABLE produto (
    id_produto int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(45) NOT NULL,
    descricao varchar(100) NOT NULL,
    categoria varchar(20) NOT NULL,
    sku varchar(10) UNIQUE NOT NULL,
    quantidade int NOT NULL CHECK (quantidade >= 0),
    estoque_minimo int NOT NULL CHECK (estoque_minimo >= 0),
    preco_custo numeric(6, 2) NOT NULL CHECK (preco_custo >= 0),
    preco_venda numeric(6, 2) NOT NULL CHECK (preco_venda >= 0),
    localizacao varchar(5) NOT NULL,
    data_cadastro timestamp DEFAULT CURRENT_TIMESTAMP,
    ativo boolean DEFAULT true
);