CREATE TABLE fornecedor (
    id_fornecedor int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome varchar(45) NOT NULL,
    telefone varchar(20) NOT NULL,
    email varchar (70) NOT NULL,
    endereco varchar (100) NOT NULL,
    ativo boolean DEFAULT true
);