CREATE TABLE movimentacao (
    id_movimentacao int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_produto int REFERENCES produto(id_produto) NOT NULL,
    tipo varchar (7) CHECK (tipo IN ('Entrada', 'Saida')) NOT NULL,
    quantidade int NOT NULL CHECK (quantidade >= 0),
    data_movimentacao timestamp DEFAULT CURRENT_TIMESTAMP,
    origem_destino varchar(50) NOT NULL
);